export const LOGIN_REQUEST= "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";


export const CATEGORY_LIST = "CATEGORY_LIST";
export const CATEGORY_LIST_RECEIVED = "CATEGORY_LIST_RECEIVED";

export const CATEGORY_CHANNEL_LIST = "CATEGORY_CHANNEL_LIST";
export const CATEGORY_CHANNEL_LIST_RECEIVED = "CATEGORY_CHANNEL_LIST_RECEIVED";

export const CHANNEL_STREAM_REQUEST = "CHANNEL_STREAM_REQUEST";
export const CHANNEL_STREAM_RECEIVED = "CHANNEL_STREAM_RECEIVED";


export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_RECEIVED = "USER_DETAILS_RECEIVED";

export const EVENTS_REQUEST = "EVENTS_REQUEST";
export const EVENTS_RESPONSE = "EVENTS_RESPONSE";
//export const  = "";
